```{r}
#Proyecto

#1. Conocimiento de los datos

  #1.1 Cargue el paquete tidyverse.
library(tidyverse)
  #1.2 
yearly <- read_csv("deaths_handwashing.csv")
  #1.3
yearly
```
```{r}
#2. El alarmante número de muertes
  #2.1 
yearly %>%
  mutate(proportion_deaths= deaths/births)
  #2.2
```

```{r}
#3. Muerte en las clinicas
  #3.1 & 3.2
library(ggplot2)
dt_yearly <-yearly %>%
  mutate(proportion_deaths= deaths/births)

ggplot(dt_yearly, aes(x=year, y=proportion_deaths,color=clinic)) + geom_line()
```
```{r}
#4. Comienza el lavado de manos
  #4.1
monthly <- read_csv("deaths_clinic_1.csv")
  #4.2 & 4.3
monthly %>%
  mutate(proportion_deaths=deaths/births) %>%
  head()

```
```{r}
#5 El efecto del lavado de manos
  #5.1
dt_monthly <- monthly %>%
  mutate(proportion_deaths=deaths/births)
ggplot(dt_monthly, aes(x=date, y=proportion_deaths)) + geom_line()
```

```{r}
  #5.2
ggplot(dt_monthly, aes(x=date, y=proportion_deaths)) + geom_line() + xlab("Date") + ylab("Proportion_deaths") + theme_classic()
```
```{r}
  #5.3
death_by_year <- monthly %>%
  mutate(proportion_deaths=deaths/births) %>%
  mutate(year=year(date)) %>%
  group_by(year)%>%
  summarise(mean_pdeaths=mean(proportion_deaths))
death_by_year
```
```{r}
  #5.4
ggplot(death_by_year, aes(x=year, y=mean_pdeaths)) + geom_bar(stat="identity")
```
```{r}
#6. Los resultados del lavado de manos
  #6.1 
monthly %>%
  mutate(handwashing_stard=year(date)>=1847)
```
```{r}
  #6.2 & 6.3
dt_monthly <-monthly %>%
  mutate(handwashing_started=year(date)>=1847)%>%
  mutate(proportion_deaths=deaths/births)
ggplot(dt_monthly, aes(x=date,y=proportion_deaths,color=handwashing_started)) + geom_line() + xlab("Date") + ylab("Proportion_deaths") + theme_classic() 
```

